#!/bin/sh

# allow read/write in application home folder
mkdir -m 777 "$SYNOPKG_PKGDEST/data"
chown -R admin.users "$SYNOPKG_PKGDEST/data"

# create /usr/local/bin/[package] program link
ln -s "$SYNOPKG_PKGDEST/$SYNOPKG_PKGNAME.sh" "/usr/local/bin/$SYNOPKG_PKGNAME"

# create /usr/local/[package] link
ln -s "$SYNOPKG_PKGDEST" "/usr/local/$SYNOPKG_PKGNAME"

# return successfully
exit 0
