#!/bin/sh

# allow read/write in application home folder
mkdir -m 777 "$SYNOPKG_PKGDEST/data"
chown -R admin.users "$SYNOPKG_PKGDEST/data"

# create /usr/local/[package] link
ln -s "/var/packages/$SYNOPKG_PKGNAME/target" "/usr/local/$SYNOPKG_PKGNAME"

# return successfully
exit 0
